// Contains the script with which to randomly generate a scenario.

// Narrative arc.
var arc = [
    'Collapse (a few years)',
    'Collapse (a decade)',
    'Collapse (a generation)',
    'Collapse (two generations)',
    'Collapse (a century)',
    'Collapse (a millenium)',
    'Discipline (a few years)',
    'Discipline (a decade)',
    'Discipline (a generation)',
    'Discipline (two generations)',
    'Discipline (a century)',
    'Discipline (a millenium)',
    'Grow (a few years)',
    'Grow (a decade)',
    'Grow (a generation)',
    'Grow (two generations)',
    'Grow (a century)',
    'Grow (a millenium)',
    'Transform (a few years)',
    'Transform (a decade)',
    'Transform (a generation)',
    'Transform (two generations)',
    'Transform (a century)',
    'Transform (a millenium)',
];

// Terrain.
var terrain = [
    'Agriculture',
    'Citizenship',
    'Cloning',
    'Disease',
    'The brain',
    'Class',
    'Communications',
    'Drones',
    'Childhood',
    'Climate',
    'Court',
    'The economy',
    'Edcation',
    'Entertainment',
    'Environment',
    'Equality',
    'Family',
    'Flight',
    'Forests',
    'Genetics',
    'Gender',
    'Governance',
    'Health',
    'Hobbies',
    'Home',
    'Identity',
    'Insects',
    'Intellectual property',
    'Journalism',
    'Justice',
    'Learning',
    'Memory',
    'Mining',
    'The moon',
    'Oceans',
    'Oil',
    'Old age',
    'Pets',
    'Power',
    'Religion',
    'Robots',
    'Sex',
    'Shopping',
    'Learning',
    'Space',
    'Sports',
    'Theatre',
    'Travel',
    'War',
    'Water',
    'Wealth',
    'Women',
    'Work',
    'Zombies',
    'The zoo',
];

// Object.
var object = [
    'Advertisement',
    'Artwork',
    'Beverage',
    'Book',
    'Bottle',
    'Box',
    'Brochure',
    'Building',
    'Candy',
    'Clothing',
    'Device',
    'Document',
    'Event',
    'Festival',
    'Flag',
    'MEDO',
    'Game',
    'Headline',
    'Implant',
    'Instrument',
    'Jewelery',
    'Kit',
    'Law',
    'Logo',
    'Lotion',
    'Machine',
    'Magazine Cover',
    'Map',
    'Mask',
    'Monument',
    'Passport',
    'Pill',
    'Plant',
    'Postcard',
    'Poster',
    'Product',
    'Prosthetic',
    'Public Service Annoucement',
    'Relic',
    'Ritual',
    'Show',
    'Slogan',
    'Snack',
    'Song',
    'Souvenir',
    'Statue',
    'Sticker',
    'Symbol',
    'T-Shirt',
    'Tattoo',
    'Tool',
    'Vehicle',
    'Video',
    'Weapon',
];

// Mood.
var mood = [
    'Admiration',
    'Alientation',
    'Amusement',
    'Anger',
    'Anxiety',
    'Awkwardness',
    'Calm',
    'Charm',
    'Cheer',
    'Contentment',
    'Curiosity',
    'Decadence',
    'Delight',
    'Disgust',
    'Dread',
    'Embarassment',
    'Excitement',
    'Exhiliration',
    'Fascination',
    'Fervor',
    'Frustration',
    'Gratitude',
    'Happiness',
    'Hilarity',
    'Hope',
    'Longing',
    'Malaise',
    'Melancholy',
    'Melodrama',
    'Nostalgia',
    'Optimism',
    'Outrage',
    'Pathos',
    'Pleasure',
    'Pride',
    'Rationality',
    'Relief',
    'Resentment',
    'Respect',
    'Sadness',
    'Satisfaction',
    'Serenity',
    'Shame',
    'Shock',
    'Sorrow',
    'Surprise',
    'Unease',
    'Warmth',
    'Weirdness',
    'Wellbeing',
    'Wonder',
    'Worry',
    'Zen'
];

// TODO Fix newline characters here for nicer spacing.
function generateScenario(arc,terrain,object,mood)
{
    var outcome = "A scenario  with the arc: " + arc[Math.floor(Math.random() * arc.length)];
    outcome += "\n the terrain: " + terrain[Math.floor(Math.random() * terrain.length)];
    outcome += "\n the object: " + object[Math.floor(Math.random() * object.length)];
    outcome += "\n and the mood: " + mood[Math.floor(Math.random() * mood.length)] + ".";
    return outcome;
}

var outcome = generateScenario(arc,terrain,object,mood);
var containerElement = document.getElementById('me');
var outcomeElement = document.createTextNode(outcome);
containerElement.appendChild(outcomeElement); 